### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by curtisblackwell** [thefriendlybeasts/wordles-with-friends#1]
- [ ] Fix Safari bugs
  - [ ] colors = bad
- [ ] Auto-focus on first letter of next guess after an incorrect guess
- [ ] Choose a domain
- [ ] Configure a domain
- [ ] Accessible sharing of results
  - [ ] Could include a link to the puzzle
- [ ] Try older versions of SvelteKit to see if we can get around the bug
- [ ] Show used/unused letter on-screen
